version: '2.1'
services:
  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_rest_django
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql_db", "-u", "mysql", "-ppassword"]
      timeout: 20s
      retries: 10
    networks:
      - app-tier
    restart: always

  web:
    build: .
    depends_on:
      - migration
      - mysql_db
    volumes:
      - .:/galenos_project
    networks:
      - app-tier
    ports:
      - "8000:8000"
    command: python /galenos_project/manage.py runserver 0:8000
    restart: always

  migration:
    build: .
    volumes:
      - .:/galenos_project
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - app-tier
    command: sh -c "python /galenos_project/manage.py makemigrations --noinp>
    restart: always

networks:
  app-tier:
    driver: bridge
